# Generated by Django 4.2 on 2023-05-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('apodo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('mins', models.IntegerField()),
                ('sec', models.IntegerField()),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('author', models.CharField(max_length=25)),
                ('views', models.CharField(max_length=11)),
                ('link', models.CharField(max_length=300)),
                ('gif', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
