# Generated by Django 4.2 on 2023-05-01 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamer',
            old_name='apodo',
            new_name='username',
        ),
    ]
