# Generated by Django 4.2 on 2023-05-01 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_apodo_streamer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='title',
            new_name='Titulo',
        ),
    ]
